version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: laravel_nginx
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "7000:80"
    networks:
      - laravel
  
  db:
    image: mariadb:10.4
    volumes:
      - ./mysql:/var/lib/mysql
    container_name: laravel_db
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./src:/var/www/html"
    container_name: laravel_php
    ports:
      - "9004:9004"
    networks:
      - laravel
  
  composer:
    image: composer:latest
    container_name: laravel_composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
      - php
    networks:
      - laravel